name = "curvint"
version = "0.1.0"
defaultTargets = ["Curvint"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
pp.proofs.withType = false

[[lean_lib]]
name = "Curvint"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "1b34e3c465be11c640713935e6014bd820dcc1a0"
